-- CreateTable
CREATE TABLE "USE_USERS" (
    "USE_ID" SERIAL NOT NULL,
    "USE_USERNAME" TEXT NOT NULL,
    "USE_PASSWORD" TEXT NOT NULL,
    "USE_NAME" TEXT NOT NULL,
    "USE_LASTNAME" TEXT NOT NULL,

    CONSTRAINT "USE_USERS_pkey" PRIMARY KEY ("USE_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USE_USERS_USE_USERNAME_key" ON "USE_USERS"("USE_USERNAME");
